name: kanade
description: "Android app to extract apks from installed apps (Android 4.4+)."
publish_to: "none"
version: 0.5.0+7

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  device_packages:
    path: ../device_packages/device_packages
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_shared_tools:
    git:
      url: https://github.com/alexrintt/flutter-shared-tools
      ref: master
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: ^4.8.0
  nanoid: ^1.0.0
  package_info_plus: ^3.0.1
  path: ^1.8.2
  pixelarticons: ^0.4.0
  provider: ^6.0.5
  share_plus: 6.3.1
  shared_preferences: ^2.0.15
  shared_storage:
    path: ../shared-storage
  string_similarity: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  lint: ^2.0.1


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/bottom.png
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 700
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: Forward
      fonts:
        - asset: assets/fonts/Forward.ttf
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: assets/fonts/ZenKakuGothicAntique-Regular.ttf
