name: kanade
description: "Kanade is a simple app that allows you to extract apk from your apps list. Fully open-source and zero-ads."
publish_to: "none"
version: 0.4.0+6

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  device_apps:
    git:
      url: https://github.com/alexrintt/flutter_plugin_device_apps
      ref: 6051e51fd78778f848eca870ec51a0367b5d2fd9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_shared_tools:
    git:
      url: https://github.com/alexrintt/flutter-shared-tools
      ref: master
  fluttertoast: ^8.0.8
  get_it: ^7.2.0
  intl: ^0.17.0
  nanoid: ^1.0.0
  package_info_plus: ^3.0.1
  pixelarticons: ^0.4.0
  shared_preferences: ^2.0.15
  shared_storage: ^0.6.0
  string_similarity: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/bottom.png
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 700
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: Forward
      fonts:
        - asset: assets/fonts/Forward.ttf
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: assets/fonts/ZenKakuGothicAntique-Regular.ttf
