name: kanade
description: "🌾 Minimal Dark and Monochrome Apk Extractor App available for Android 4.4+"
publish_to: "none"
version: 0.3.2+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_storage: ^0.6.0
  device_apps:
    git:
      url: https://github.com/alexrintt/flutter_plugin_device_apps
      ref: 6051e51fd78778f848eca870ec51a0367b5d2fd9
  flutter_shared_tools:
    git:
      url: https://github.com/alexrintt/flutter-shared-tools
      ref: master
  get_it: ^7.2.0
  nanoid: ^1.0.0
  fluttertoast: ^8.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.0.15
  pixelarticons: ^0.4.0
  url_launcher: ^6.1.6
  package_info_plus: ^3.0.1
  intl: ^0.17.0
  string_similarity: ^2.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/bottom.png
  fonts:
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
          weight: 700
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: Forward
      fonts:
        - asset: assets/fonts/Forward.ttf
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: assets/fonts/ZenKakuGothicAntique-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/launcher.png"
