name: kanade
description: "🌾 Minimal Dark and Monochrome Apk Extractor App available for Android 4.4+"
publish_to: "none"
version: 0.1.1-alpha

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  shared_storage: ^0.4.0
  device_apps:
    git:
      url: https://github.com/lakscastro/flutter_plugin_device_apps
      ref: 6051e51fd78778f848eca870ec51a0367b5d2fd9
  get_it: ^7.2.0
  url_launcher: ^6.0.12
  nanoid: ^1.0.0
  path: ^1.8.0
  fluttertoast: ^8.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bottom.png
    - assets/images/pixel_animation.gif
  fonts:
    - family: PixelArt
      fonts:
        - asset: assets/fonts/PixelArt.ttf
    - family: Inconsolata
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
        - asset: assets/fonts/Inconsolata-Bold.ttf
          weight: 700
    - family: Forward
      fonts:
        - asset: assets/fonts/Forward.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icons/launcher.png"
