name: Build MkDocs
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish new app doc version"]
    types:
      - completed
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./website
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: website/mkdocs.yaml
          REQUIREMENTS: website/requirements.txt
          EXTRA_PACKAGES: build-base
