name: Validate fastlane actions
run-name: Validation triggered by @${{ github.actor }}

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  validate-fastlane:
    # required to run on Linux because this is a docker container action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ashutoshgngwr/validate-fastlane-supply-metadata@v2
